services:
  mysql:
    image: 'mysql:8.4.7'
    container_name: tally-mysql
    environment:
      MYSQL_DATABASE: tally_db
      MYSQL_ROOT_PASSWORD: ${ROOT_PASS}
      MYSQL_USER: tally_user
      MYSQL_PASSWORD: ${MYSQL_PASS}
    ports:
      - '3306:3306'
    volumes:
      - tally_data:/var/lib/mysql
    healthcheck:
      test: [ "CMD", "mysqladmin" ,"ping", "-h", "localhost" ]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  tally_data: