spring.application.name=TallyAPI

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

spring.datasource.url=jdbc:mysql://localhost:3306/tally_db
spring.datasource.username=tally_user
spring.datasource.password=tally_pass
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
